# Generated by Django 5.2 on 2025-04-27 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_id', message='מספר תעודת זהות חייב להכיל בדיוק 9 ספרות.', regex='^\\d{9}$')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
