# Generated by Django 5.2 on 2025-05-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productcategory_productoption_userselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availablemeeting',
            name='location',
            field=models.CharField(default='נווה שאנן 134', max_length=255, verbose_name='מיקום הפגישה'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchasedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('building_number', models.CharField(max_length=10)),
                ('floor_number', models.CharField(blank=True, max_length=10, null=True)),
                ('apartment_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
